source 'http://rubygems.org'

gem 'middleman', '~>3.3.7'
gem 'slim', '~> 2.0'
gem 'middleman-livereload', '~> 3.1.0'
gem 'middleman-dotenv'
gem 'middleman-sync'
gem 'middleman-cloudfront'
gem 'middleman-blog'
gem 'middleman-s3_sync'
gem 'middleman-imageoptim'
gem 'byebug'
gem 'builder'
